### ISSUE TITLE
apparently broken for weeks

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi.github.io#61]
![image](https://github.com/dandi/dandi.github.io/assets/39889/43728d3b-5f39-4585-b0dd-4bb09e9b792b)

looking into it

**Comment by yarikoptic** [comment]
```
Warning:  github-pages can't satisfy your Gemfile's dependencies.
To use retry middleware with Faraday v2.0+, install `faraday-retry` gem
/usr/local/bundle/gems/safe_yaml-1.0.5/lib/safe_yaml/load.rb:143:in `parse': (/github/workspace/_data/team_members.yml): did not find expected key while parsing a block mapping at line 87 column 3 (Psych::SyntaxError)
	from /usr/local/bundle/gems/safe_yaml-1.0.5/lib/safe_yaml/load.rb:143:in `load'
	from /usr/local/bundle/gems/safe_yaml-1.0.5/lib/safe_yaml/load.rb:157:in `block in load_file'
	from /usr/local/bundle/gems/safe_yaml-1.0.5/lib/safe_yaml/load.rb:157:in `open'
	from /usr/local/bundle/gems/safe_yaml-1.0.5/lib/safe_yaml/load.rb:157:in `load_file'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/readers/data_reader.rb:66:in `read_data_file'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/readers/data_reader.rb:46:in `block in read_data_to'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/readers/data_reader.rb:38:in `each'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/readers/data_reader.rb:38:in `read_data_to'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/readers/data_reader.rb:20:in `read'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/reader.rb:18:in `read'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/site.rb:164:in `read'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/site.rb:69:in `process'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/command.rb:28:in `process_site'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/commands/build.rb:65:in `build'
	from /usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/commands/build.rb:[36](https://github.com/dandi/dandi.github.io/actions/runs/6907921231/job/18796095926#step:4:37):in `process'
	from /usr/local/bundle/gems/github-pages-228/bin/github-pages:70:in `block (3 levels) in <top (required)>'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary/program.rb:[42](https://github.com/dandi/dandi.github.io/actions/runs/6907921231/job/18796095926#step:4:43):in `go'
	from /usr/local/bundle/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
	from /usr/local/bundle/gems/github-pages-228/bin/github-pages:6:in `<top (required)>'
	from /usr/local/bundle/bin/github-pages:23:in `load'
	from /usr/local/bundle/bin/github-pages:23:in `<main>'
Error:  Logging at level: debug Configuration file: /github/workspace/./_config.yml GitHub Pages: github-pages v228 GitHub Pages: jekyll v3.9.3 Theme: jekyll-theme-primer Theme source: /usr/local/bundle/gems/jekyll-theme-primer-0.6.0 Requiring: jekyll-github-metadata Requiring: jekyll-seo-tag Requiring: jekyll-coffeescript Requiring: jekyll-commonmark-ghpages Requiring: jekyll-gist Requiring: jekyll-github-metadata Requiring: jekyll-paginate Requiring: jekyll-relative-links Requiring: jekyll-optional-front-matter Requiring: jekyll-readme-index Requiring: jekyll-default-layout Requiring: jekyll-titles-from-headings GitHub Metadata: Initializing... Source: /github/workspace/. Destination: /github/workspace/./_site Incremental build: disabled. Enable with --incremental Generating... EntryFilter: excluded /Gemfile EntryFilter: excluded /CNAME EntryFilter: excluded /Gemfile.lock Reading: _posts/2022-03-08-microscopy-workshop.md Reading: _posts/2021-10-13-dandi-workshop.md Reading: _posts/2021-09-12-introducing-dandi.md Reading: _posts/2022-03-03-external-links-organize.md github-pages 228 | Error: (/github/workspace/_data/team_members.yml): did not find expected key while parsing a block mapping at line 87 column 3
```

likely broken by dc89149226c5d431d3f9003e3d144653da919866

**Comment by yarikoptic** [comment]
fixed by https://github.com/dandi/dandi.github.io/commit/8d290c6bd9e7aa79f6baefc62c76a9ca01f31583
